version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
pre_build:
  commands:
    - echo "Logging in to Amazon ECR..."
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 192706391702.dkr.ecr.ap-southeast-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build and push completed successfully
      - echo "Post-build phase executed"

artifacts:
  files:
    - '**/*'
